services:
    postgres:
        image: postgres:16
        container_name: reliefroot-postgres
        restart: unless-stopped

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: reliefroot

        ports:
            - "5433:5432"

        volumes:
            - reliefroot_postgres_data:/var/lib/postgresql/data

volumes:
    reliefroot_postgres_data:
